version: '3.3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - app-network
    volumes:
      - zookeeper-data:/bitnami/zookeeper  # Persist Zookeeper data store outside container

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - app-network
    volumes:
      - kafka-data:/bitnami/kafka  # Persist Kafka data store outside container

  orderservice:
    environment:
      - PRODUCT_SERVICE_URL=https://springboot-aws-eks-ordermanagementsystem.onrender.com/api/products
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}  # Dynamically set profile

  productservice:
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}  # Dynamically set profile

  nginx:
    image: nginx:latest
    ports:
      - "7777:80"  # Expose NGINX on port 7777
    depends_on:
      - orderservice
      - productservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX config file
    networks:
      - app-network

volumes:
  zookeeper-data:  # Volume for Zookeeper data store outside container
    driver: local
  kafka-data:  # Volume for Kafka data store outside container
    driver: local
networks:
  app-network:
    driver: bridge
