version: '3.3'

services:
  orderservice:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - PRODUCT_SERVICE_URL=http://productservice:8083/api/products
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - app-network

  productservice:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - orderservice
      - productservice
