apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: 756639706743.dkr.ecr.ap-south-1.amazonaws.com/order-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials-order
                  key: db.url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials-order
                  key: db.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-order
                  key: db.password

# kubectl create secret generic db-credentials
#  --from-literal=db.url=jdbc:mysql://orderdb.cf4ykim046yo.ap-south-1.rds.amazonaws.com:3306/orders --from-literal=db.username=varsharoot --from-literal=db.password=varsharoot
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
